"""
Embedding cache key derivation.

The cache key is derived from the chunk text plus the full identity of
the provider that would generate its embedding (provider, model, and
configuration fingerprint). Including provider identity is essential:
without it, switching providers or models would silently return a
vector generated by a different embedding space.
"""

from __future__ import annotations

import hashlib

from app.ai.knowledge.embeddings.enums import EmbeddingProvider

_KEY_PREFIX = "embedding-cache"


def build_embedding_cache_key(
    *,
    provider: EmbeddingProvider,
    model: str,
    configuration_fingerprint: str,
    text: str,
) -> str:
    """
    Build a stable cache key for a chunk's embedding.

    Args:
        provider:
            Embedding provider that would generate the vector.

        model:
            Embedding model name.

        configuration_fingerprint:
            Stable fingerprint of the provider's configuration.

        text:
            Chunk text to be embedded.

    Returns:
        A namespaced, stable cache key.
    """

    digest = hashlib.sha256(
        "\x1f".join(
            [
                provider.value,
                model,
                configuration_fingerprint,
                text,
            ]
        ).encode("utf-8")
    ).hexdigest()

    return f"{_KEY_PREFIX}:{provider.value}:{digest}"
