"""
No-op embedding cache.

Used as the default when no cache is configured, so EmbeddingService
behaves exactly as it did before caching was introduced: every chunk is
a cache miss, and every embedding is generated by the provider.
"""

from __future__ import annotations

from app.ai.knowledge.cache.embeddings.interfaces import EmbeddingCache


class NullEmbeddingCache(EmbeddingCache):
    """
    Embedding cache that never stores or returns anything.
    """

    async def get_many(
        self,
        keys: list[str],
    ) -> dict[str, list[float]]:
        return {}

    async def set_many(
        self,
        entries: dict[str, list[float]],
    ) -> None:
        return None
