GENERATION_REQUESTS_TOTAL = "generation_requests_total"

GENERATION_FAILURES_TOTAL = "generation_failures_total"

GENERATION_RETRIES_TOTAL = "generation_retries_total"

GENERATION_REGENERATIONS_TOTAL = "generation_regenerations_total"

GENERATION_CACHE_HITS_TOTAL = "generation_cache_hits_total"

GENERATION_VALIDATION_FAILURES_TOTAL = "generation_validation_failures_total"

GENERATION_HALLUCINATION_FLAGS_TOTAL = "generation_hallucination_flags_total"

GENERATION_RUNTIME_VALIDATION_FAILURES_TOTAL = "generation_runtime_validation_failures_total"
